name: session
description: Network request result.
version: 1.0.5
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.0.1 # https://github.com/flutterchina/dio
