name: session
description: Network request result.
version: 1.1.1
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  dio: ^5.1.1 # https://github.com/flutterchina/dio
