name: session
description: Network request result.
version: 1.2.0
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  dio: ^5.4.0 # https://github.com/cfug/dio
