name: session
description: Network request result.
version: 1.1.2
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dio: ^5.1.2 # https://github.com/flutterchina/dio
