name: session
description: Network request result.
version: 1.4.0
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.13.0 <4.0.0"

dependencies:
  dio: ^5.8.0+1 # https://github.com/cfug/dio
