name: session
description: Network request result.
version: 1.1.7
homepage: https://github.com/OctMon/session

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:
  dio: ^5.4.0 # https://github.com/cfug/dio
