name: session
description: Network request result
version: 0.3.6
author: OctMon <octmon@qq.com>
homepage:  https://github.com/OctMon/session

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^2.1.13 # https://github.com/flutterchina/dio
