name: session
description: Network request result
version: 0.4.1
author: OctMon <octmon@qq.com>
homepage:  https://github.com/OctMon/session

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.8 # https://github.com/flutterchina/dio
