name: session
description: Network request result
version: 0.2.0
author: OctMon <octmon@qq.com>
homepage:  https://github.com/OctMon/session

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^2.1.3 # https://github.com/flutterchina/dio
