name: session
description: Network request result
version: 0.5.1
homepage:  https://github.com/OctMon/session

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  dio: ^3.0.9 # https://github.com/flutterchina/dio
